# -*- coding: utf-8 -*-
"""register.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp30NPXICW1iuEUWqDgw1M8oJOXXk8bN
"""

import cv2
import torch
import numpy as np
from facenet_pytorch import InceptionResnetV1, MTCNN
import pyodbc

# ------------------- INPUT -------------------
name = input("Enter your name: ")

# ------------------- MODELS -------------------
device = 'cuda' if torch.cuda.is_available() else 'cpu'
mtcnn = MTCNN(keep_all=False, device=device)
resnet = InceptionResnetV1(pretrained='vggface2').eval().to(device)

# ------------------- DB -------------------
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=RP\\SQLEXPRESS;"
    "DATABASE=att_db;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

# ------------------- CAMERA -------------------
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

print("Press 's' to save face, ESC to exit")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    #  Resize for speed
    frame = cv2.resize(frame, (640, 480))

    cv2.imshow("Register Face", frame)

    key = cv2.waitKey(1) & 0xFF

    if key == ord('s'):
        print("📸 Capturing face...")

        #  smaller frame for faster detection
        small_frame = cv2.resize(frame, (320, 240))

        try:
            face = mtcnn(small_frame)
        except:
            print("Error detecting face")
            continue

        if face is not None:
            print(" Processing embedding...")

            emb = resnet(face.unsqueeze(0).to(device))
            emb = emb.detach().cpu().numpy()[0]

            #  FIXED BINARY INSERT
            cursor.execute(
                "INSERT INTO users (name, embedding) VALUES (?, ?)",
                name, pyodbc.Binary(emb.tobytes())
            )
            conn.commit()

            print(f" {name} registered successfully!")
            break
        else:
            print("No face detected. Stay still and try again.")

    elif key == 27:
        break

cap.release()
cv2.destroyAllWindows()

