# -*- coding: utf-8 -*-
"""sm_att.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXvFZ731YgnA0j_b1kHdIxLPijwC4Eav
"""

import cv2
import numpy as np
import torch
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
from facenet_pytorch import InceptionResnetV1, MTCNN
from datetime import datetime
import pyodbc
import smtplib

# ------------------- MODELS -------------------
yolo = YOLO("yolov8n.pt")
tracker = DeepSort(max_age=30)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
mtcnn = MTCNN(keep_all=False, device=device)
resnet = InceptionResnetV1(pretrained='vggface2').eval().to(device)

# ------------------- DATABASE -------------------
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=RP\\SQLEXPRESS;"
    "DATABASE=att_db;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

# Load known faces
cursor.execute("SELECT id, name, embedding FROM users")
rows = cursor.fetchall()

known_embeddings = []
names = []
ids = []

for r in rows:
    ids.append(r[0])
    names.append(r[1])
    known_embeddings.append(np.frombuffer(r[2], dtype=np.float32))

# ------------------- EMAIL -------------------
def send_email(name):
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login("remendia1@gmail.com", "jeju yqpk vubl ofrk")

        msg = f"{name} marked present at {datetime.now()}"
        server.sendmail("remendia1@gmail.com", "shapinto219@gmail.com", msg)

        server.quit()
    except Exception as e:
        print("Email failed:", e)

# ------------------- MATCH FUNCTION -------------------
def match_face(embedding):
    for i, known in enumerate(known_embeddings):
        dist = np.linalg.norm(embedding - known)
        if dist < 0.8:
            return ids[i], names[i]
    return None, "Unknown"

# ------------------- DUPLICATE CONTROL -------------------
last_seen = {}
THRESHOLD_TIME = 60

# ------------------- CAMERA -------------------
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame = cv2.resize(frame, (640, 480))

    results = yolo(frame)

    detections = []
    for r in results:
        for box in r.boxes.xyxy:
            x1, y1, x2, y2 = map(int, box)
            detections.append(([x1, y1, x2-x1, y2-y1], 1.0, 'face'))

    tracks = tracker.update_tracks(detections, frame=frame)

    for track in tracks:
        if not track.is_confirmed():
            continue

        x1, y1, x2, y2 = map(int, track.to_ltrb())

        # SAFE CROP
        face_crop = frame[y1:y2, x1:x2]

        if face_crop is None or face_crop.size == 0:
            continue

        h, w, _ = face_crop.shape
        if h < 50 or w < 50:
            continue

        # SAFE MTCNN
        try:
            aligned = mtcnn(face_crop)
        except:
            continue

        if aligned is None:
            continue

        name = "Unknown"

        emb = resnet(aligned.unsqueeze(0).to(device))
        emb = emb.detach().cpu().numpy()[0]

        user_id, name = match_face(emb)

        if user_id:
            now = datetime.now()

            if user_id not in last_seen or (now - last_seen[user_id]).seconds > THRESHOLD_TIME:

                cursor.execute(
                    "INSERT INTO attendance (user_id, date, time, status) VALUES (?, ?, ?, ?)",
                    user_id, now.date(), now.time(), "Present"
                )
                conn.commit()

                last_seen[user_id] = now

                print(f"{name} marked present")
                send_email(name)

        # Draw
        cv2.rectangle(frame, (x1,y1),(x2,y2),(255,0,0),2)
        cv2.putText(frame, name, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2)

    cv2.imshow("Smart Attendance System", frame)

    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()